[package]
name = "movement"
version = "0.1.0"
edition = "2024"

[dependencies]
defmt = "1.0.1"
fixed = "1.29.0"
fixed-sqrt = "0.3.0"
tokio = "1.48.0"

[dependencies.derive_more]
version = "2.0.1"
default-features = false
features = ["from", "into", "display", "debug"]
